# Generated by Django 6.0.7 on 2026-08-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('detector', 'Detector'), ('classificador', 'Classificador')], default='detector', max_length=50)),
                ('versao', models.CharField(max_length=50)),
                ('arquivo', models.CharField(blank=True, max_length=500, verbose_name='Caminho do peso')),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modelo de IA',
                'verbose_name_plural': 'Modelos de IA',
                'ordering': ['nome'],
                'unique_together': {('nome', 'versao')},
            },
        ),
    ]
