# Generated by Django 6.0.7 on 2026-08-05 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linhas', to='produtos.produto', verbose_name='Produto inspecionado')),
            ],
            options={
                'verbose_name': 'Linha',
                'verbose_name_plural': 'Linhas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('identificador', models.CharField(max_length=255, verbose_name='Identificador (IP/URL)')),
                ('tipo', models.CharField(choices=[('ip', 'IP'), ('usb', 'USB'), ('stream', 'Stream')], default='ip', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cameras', to='configuracao.linha')),
            ],
            options={
                'verbose_name': 'Câmera',
                'verbose_name_plural': 'Câmeras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflows', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('deteccao', 'Detecção'), ('classificacao', 'Classificação'), ('destino', 'Destino')], max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='configuracao.workflow')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'ordering': ['ordem'],
                'unique_together': {('workflow', 'ordem')},
            },
        ),
    ]
